/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package softwarea3;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Random;


/**
 *
 * @author PUPO, PAGUE UM PAU
 */
public class TelaGrupos extends javax.swing.JFrame {

    /**
     * Creates new form TelaGrupos
     */
    public TelaGrupos() {
        initComponents();
        getTimes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gruposOficiaisButton = new javax.swing.JButton();
        simulaGruposButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        time1Grupo1TextField = new javax.swing.JTextField();
        time2Grupo1TextField = new javax.swing.JTextField();
        time3Grupo1TextField = new javax.swing.JTextField();
        time4Grupo1TextField = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        time1Grupo2TextField = new javax.swing.JTextField();
        time2Grupo2TextField = new javax.swing.JTextField();
        time3Grupo2TextField = new javax.swing.JTextField();
        time4Grupo2TextField = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        time1Grupo3TextField = new javax.swing.JTextField();
        time2Grupo3TextField = new javax.swing.JTextField();
        time3Grupo3TextField = new javax.swing.JTextField();
        time4Grupo3TextField = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        time1Grupo6TextField = new javax.swing.JTextField();
        time2Grupo6TextField = new javax.swing.JTextField();
        time3Grupo6TextField = new javax.swing.JTextField();
        time4Grupo6TextField = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        time1Grupo4TextField = new javax.swing.JTextField();
        time2Grupo4TextField = new javax.swing.JTextField();
        time3Grupo4TextField = new javax.swing.JTextField();
        time4Grupo4TextField = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        time1Grupo5TextField = new javax.swing.JTextField();
        time2Grupo5TextField = new javax.swing.JTextField();
        time3Grupo5TextField = new javax.swing.JTextField();
        time4Grupo5TextField = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        time1Grupo7TextField = new javax.swing.JTextField();
        time2Grupo7TextField = new javax.swing.JTextField();
        time3Grupo7TextField = new javax.swing.JTextField();
        time4Grupo7TextField = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        time1Grupo8TextField = new javax.swing.JTextField();
        time2Grupo8TextField = new javax.swing.JTextField();
        time3Grupo8TextField = new javax.swing.JTextField();
        time4Grupo8TextField = new javax.swing.JTextField();
        voltarButton = new javax.swing.JButton();
        registrarTimesButton = new javax.swing.JButton();
        mostrarJogosButton = new javax.swing.JButton();
        avancarButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grupos");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        gruposOficiaisButton.setText("Grupos Oficiais");
        gruposOficiaisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gruposOficiaisButtonActionPerformed(evt);
            }
        });

        simulaGruposButton.setText("Simular");
        simulaGruposButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulaGruposButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupo A"));
        jPanel1.setMaximumSize(new java.awt.Dimension(150, 250));
        jPanel1.setMinimumSize(new java.awt.Dimension(150, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 250));

        time1Grupo1TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        time1Grupo1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time1Grupo1TextFieldActionPerformed(evt);
            }
        });

        time2Grupo1TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time3Grupo1TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time4Grupo1TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        time4Grupo1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time4Grupo1TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(time1Grupo1TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(time2Grupo1TextField)
                    .addComponent(time3Grupo1TextField)
                    .addComponent(time4Grupo1TextField))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(time1Grupo1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time2Grupo1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time3Grupo1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time4Grupo1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupo B"));
        jPanel9.setMaximumSize(new java.awt.Dimension(150, 200));
        jPanel9.setMinimumSize(new java.awt.Dimension(150, 200));
        jPanel9.setPreferredSize(new java.awt.Dimension(150, 200));

        time1Grupo2TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        time1Grupo2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time1Grupo2TextFieldActionPerformed(evt);
            }
        });

        time2Grupo2TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time3Grupo2TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        time3Grupo2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time3Grupo2TextFieldActionPerformed(evt);
            }
        });

        time4Grupo2TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(time1Grupo2TextField)
                    .addComponent(time2Grupo2TextField)
                    .addComponent(time3Grupo2TextField)
                    .addComponent(time4Grupo2TextField))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(time1Grupo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time2Grupo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time3Grupo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time4Grupo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupo C"));
        jPanel10.setMaximumSize(new java.awt.Dimension(150, 250));
        jPanel10.setMinimumSize(new java.awt.Dimension(150, 200));
        jPanel10.setPreferredSize(new java.awt.Dimension(150, 250));

        time1Grupo3TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time2Grupo3TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time3Grupo3TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time4Grupo3TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        time4Grupo3TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time4Grupo3TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(time1Grupo3TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(time2Grupo3TextField)
                    .addComponent(time3Grupo3TextField)
                    .addComponent(time4Grupo3TextField))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(time1Grupo3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time2Grupo3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time3Grupo3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time4Grupo3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupo F"));
        jPanel11.setMaximumSize(new java.awt.Dimension(150, 250));
        jPanel11.setMinimumSize(new java.awt.Dimension(150, 250));
        jPanel11.setPreferredSize(new java.awt.Dimension(150, 250));

        time1Grupo6TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time2Grupo6TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time3Grupo6TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time4Grupo6TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(time2Grupo6TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(time3Grupo6TextField)
                    .addComponent(time4Grupo6TextField)
                    .addComponent(time1Grupo6TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(time1Grupo6TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time2Grupo6TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time3Grupo6TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time4Grupo6TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupo D"));
        jPanel12.setMaximumSize(new java.awt.Dimension(150, 250));
        jPanel12.setMinimumSize(new java.awt.Dimension(150, 250));
        jPanel12.setPreferredSize(new java.awt.Dimension(150, 250));

        time1Grupo4TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time2Grupo4TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time3Grupo4TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time4Grupo4TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(time1Grupo4TextField)
                    .addComponent(time2Grupo4TextField)
                    .addComponent(time3Grupo4TextField)
                    .addComponent(time4Grupo4TextField))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(time1Grupo4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time2Grupo4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time3Grupo4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time4Grupo4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupo E"));
        jPanel13.setMaximumSize(new java.awt.Dimension(150, 250));
        jPanel13.setMinimumSize(new java.awt.Dimension(150, 250));
        jPanel13.setPreferredSize(new java.awt.Dimension(150, 250));

        time1Grupo5TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time2Grupo5TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time3Grupo5TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time4Grupo5TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(time1Grupo5TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(time2Grupo5TextField)
                    .addComponent(time3Grupo5TextField)
                    .addComponent(time4Grupo5TextField))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(time1Grupo5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time2Grupo5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time3Grupo5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time4Grupo5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupo G"));
        jPanel14.setMaximumSize(new java.awt.Dimension(150, 250));
        jPanel14.setMinimumSize(new java.awt.Dimension(150, 250));
        jPanel14.setPreferredSize(new java.awt.Dimension(150, 250));

        time1Grupo7TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time2Grupo7TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        time2Grupo7TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time2Grupo7TextFieldActionPerformed(evt);
            }
        });

        time3Grupo7TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time4Grupo7TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(time1Grupo7TextField)
                    .addComponent(time2Grupo7TextField)
                    .addComponent(time3Grupo7TextField)
                    .addComponent(time4Grupo7TextField))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(time1Grupo7TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time2Grupo7TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time3Grupo7TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time4Grupo7TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupo H"));
        jPanel15.setMaximumSize(new java.awt.Dimension(150, 250));
        jPanel15.setMinimumSize(new java.awt.Dimension(150, 250));
        jPanel15.setPreferredSize(new java.awt.Dimension(150, 250));

        time1Grupo8TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time2Grupo8TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time3Grupo8TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        time4Grupo8TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(time1Grupo8TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(time2Grupo8TextField)
                    .addComponent(time3Grupo8TextField)
                    .addComponent(time4Grupo8TextField))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(time1Grupo8TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time2Grupo8TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time3Grupo8TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(time4Grupo8TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        registrarTimesButton.setText("Registrar");
        registrarTimesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarTimesButtonActionPerformed(evt);
            }
        });

        mostrarJogosButton.setText("Exibir Jogos");
        mostrarJogosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarJogosButtonActionPerformed(evt);
            }
        });

        avancarButton.setText("Avançar");
        avancarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancarButtonActionPerformed(evt);
            }
        });

        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarButton)
                .addGap(84, 84, 84)
                .addComponent(limparButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gruposOficiaisButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarTimesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simulaGruposButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarJogosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avancarButton)
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(gruposOficiaisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limparButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registrarTimesButton)
                        .addComponent(simulaGruposButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(avancarButton)
                        .addComponent(mostrarJogosButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void getTimes(){
        DAO dao = new DAO();
        try{
            Time[] times = dao.getTimes();
            time1Grupo1TextField.setText(times[0].getNome());
            time2Grupo1TextField.setText(times[1].getNome());
            time3Grupo1TextField.setText(times[2].getNome());
            time4Grupo1TextField.setText(times[3].getNome());
            time1Grupo2TextField.setText(times[4].getNome());
            time2Grupo2TextField.setText(times[5].getNome());
            time3Grupo2TextField.setText(times[6].getNome());
            time4Grupo2TextField.setText(times[7].getNome());
            time1Grupo3TextField.setText(times[8].getNome());
            time2Grupo3TextField.setText(times[9].getNome());
            time3Grupo3TextField.setText(times[10].getNome());
            time4Grupo3TextField.setText(times[11].getNome());
            time1Grupo4TextField.setText(times[12].getNome());
            time2Grupo4TextField.setText(times[13].getNome());
            time3Grupo4TextField.setText(times[14].getNome());
            time4Grupo4TextField.setText(times[15].getNome());
            time1Grupo5TextField.setText(times[16].getNome());
            time2Grupo5TextField.setText(times[17].getNome());
            time3Grupo5TextField.setText(times[18].getNome());
            time4Grupo5TextField.setText(times[19].getNome());
            time1Grupo6TextField.setText(times[20].getNome());
            time2Grupo6TextField.setText(times[21].getNome());
            time3Grupo6TextField.setText(times[22].getNome());
            time4Grupo6TextField.setText(times[23].getNome());
            time1Grupo7TextField.setText(times[24].getNome());
            time2Grupo7TextField.setText(times[25].getNome());
            time3Grupo7TextField.setText(times[26].getNome());
            time4Grupo7TextField.setText(times[27].getNome());
            time1Grupo8TextField.setText(times[28].getNome());
            time2Grupo8TextField.setText(times[29].getNome());
            time3Grupo8TextField.setText(times[30].getNome());
            time4Grupo8TextField.setText(times[31].getNome());
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Preencha os campos e depois clique no botão Registrar");
        }
        
    }
    
    private void gruposOficiaisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gruposOficiaisButtonActionPerformed
        // TODO add your handling code here:
        DAO dao = new DAO();
        try {
            Time[] times = dao.getTimesOficiais();
            time1Grupo1TextField.setText(times[0].getNome());
            time2Grupo1TextField.setText(times[1].getNome());
            time3Grupo1TextField.setText(times[2].getNome());
            time4Grupo1TextField.setText(times[3].getNome());
            time1Grupo2TextField.setText(times[4].getNome());
            time2Grupo2TextField.setText(times[5].getNome());
            time3Grupo2TextField.setText(times[6].getNome());
            time4Grupo2TextField.setText(times[7].getNome());
            time1Grupo3TextField.setText(times[8].getNome());
            time2Grupo3TextField.setText(times[9].getNome());
            time3Grupo3TextField.setText(times[10].getNome());
            time4Grupo3TextField.setText(times[11].getNome());
            time1Grupo4TextField.setText(times[12].getNome());
            time2Grupo4TextField.setText(times[13].getNome());
            time3Grupo4TextField.setText(times[14].getNome());
            time4Grupo4TextField.setText(times[15].getNome());
            time1Grupo5TextField.setText(times[16].getNome());
            time2Grupo5TextField.setText(times[17].getNome());
            time3Grupo5TextField.setText(times[18].getNome());
            time4Grupo5TextField.setText(times[19].getNome());
            time1Grupo6TextField.setText(times[20].getNome());
            time2Grupo6TextField.setText(times[21].getNome());
            time3Grupo6TextField.setText(times[22].getNome());
            time4Grupo6TextField.setText(times[23].getNome());
            time1Grupo7TextField.setText(times[24].getNome());
            time2Grupo7TextField.setText(times[25].getNome());
            time3Grupo7TextField.setText(times[26].getNome());
            time4Grupo7TextField.setText(times[27].getNome());
            time1Grupo8TextField.setText(times[28].getNome());
            time2Grupo8TextField.setText(times[29].getNome());
            time3Grupo8TextField.setText(times[30].getNome());
            time4Grupo8TextField.setText(times[31].getNome());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_gruposOficiaisButtonActionPerformed

    private void time1Grupo1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time1Grupo1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time1Grupo1TextFieldActionPerformed

    private void time4Grupo1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time4Grupo1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time4Grupo1TextFieldActionPerformed

    private void time3Grupo2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time3Grupo2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time3Grupo2TextFieldActionPerformed

    private void time4Grupo3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time4Grupo3TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time4Grupo3TextFieldActionPerformed

    private void time2Grupo7TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time2Grupo7TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time2Grupo7TextFieldActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void simulaGruposButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulaGruposButtonActionPerformed
        // TODO add your handling code here:
        DAO dao = new DAO();
        try {
            Time[] grupoA = dao.getTimesPorGrupo(1);
            Time[] grupoB = dao.getTimesPorGrupo(2);
            Time[] grupoC = dao.getTimesPorGrupo(3);
            Time[] grupoD = dao.getTimesPorGrupo(4);
            Time[] grupoE = dao.getTimesPorGrupo(5);
            Time[] grupoF = dao.getTimesPorGrupo(6);
            Time[] grupoG = dao.getTimesPorGrupo(7);
            Time[] grupoH = dao.getTimesPorGrupo(8);
            
            if (grupoA.length == 0 || grupoB.length == 0 || grupoC.length == 0 || grupoD.length == 0 || grupoE.length == 0 || grupoF.length == 0 || grupoG.length == 0 || grupoH.length == 0) {
                JOptionPane.showMessageDialog(null, "Clique em registrar antes de realizar a simulação.");
            } else {

            for (int i = 0; i < 6; i++) {
                for (int j = i + 1; j < 4; j++) {
                    Random random = new Random();
                    int scoreHost = random.nextInt(4);
                    int scoreAway = random.nextInt(4);
                    Partida partida = new Partida(grupoA[i].getId(), grupoA[j].getId(), scoreHost, scoreAway);
                    if (scoreHost > scoreAway) {
                        dao.contaVitoriaHost(partida);
                    } else if (scoreHost < scoreAway) {
                        dao.contaVitoriaAway(partida);
                    } else if (scoreHost == scoreAway) {
                        dao.contaEmpate(partida);
                    }
                    dao.criaPartida(partida);
                    dao.atualizaGolsHome(partida);
                    dao.atualizaGolsAway(partida);
                }
            }
            for (int i = 0; i < 6; i++) {
                for (int j = i + 1; j < 4; j++) {
                    Random random = new Random();
                    int scoreHost = random.nextInt(4);
                    int scoreAway = random.nextInt(4);
                    Partida partida = new Partida(grupoB[i].getId(), grupoB[j].getId(), scoreHost, scoreAway);
                    if (scoreHost > scoreAway) {
                        dao.contaVitoriaHost(partida);
                    } else if (scoreHost < scoreAway) {
                        dao.contaVitoriaAway(partida);
                    } else if (scoreHost == scoreAway) {
                        dao.contaEmpate(partida);
                    }
                    dao.criaPartida(partida);
                    dao.atualizaGolsHome(partida);
                    dao.atualizaGolsAway(partida);
                }
            }
            for (int i = 0; i < 6; i++) {
                for (int j = i + 1; j < 4; j++) {
                    Random random = new Random();
                    int scoreHost = random.nextInt(4);
                    int scoreAway = random.nextInt(4);
                    Partida partida = new Partida(grupoC[i].getId(), grupoC[j].getId(), scoreHost, scoreAway);
                    if (scoreHost > scoreAway) {
                        dao.contaVitoriaHost(partida);
                    } else if (scoreHost < scoreAway) {
                        dao.contaVitoriaAway(partida);
                    } else if (scoreHost == scoreAway) {
                        dao.contaEmpate(partida);
                    }
                    dao.criaPartida(partida);
                    dao.atualizaGolsHome(partida);
                    dao.atualizaGolsAway(partida);
                }
            }
            for (int i = 0; i < 6; i++) {
                for (int j = i + 1; j < 4; j++) {
                    Random random = new Random();
                    int scoreHost = random.nextInt(4);
                    int scoreAway = random.nextInt(4);
                    Partida partida = new Partida(grupoD[i].getId(), grupoD[j].getId(), scoreHost, scoreAway);
                    if (scoreHost > scoreAway) {
                        dao.contaVitoriaHost(partida);
                    } else if (scoreHost < scoreAway) {
                        dao.contaVitoriaAway(partida);
                    } else if (scoreHost == scoreAway) {
                        dao.contaEmpate(partida);
                    }
                    dao.criaPartida(partida);
                    dao.atualizaGolsHome(partida);
                    dao.atualizaGolsAway(partida);
                }
            }
            for (int i = 0; i < 6; i++) {
                for (int j = i + 1; j < 4; j++) {
                    Random random = new Random();
                    int scoreHost = random.nextInt(4);
                    int scoreAway = random.nextInt(4);
                    Partida partida = new Partida(grupoE[i].getId(), grupoE[j].getId(), scoreHost, scoreAway);
                    if (scoreHost > scoreAway) {
                        dao.contaVitoriaHost(partida);
                    } else if (scoreHost < scoreAway) {
                        dao.contaVitoriaAway(partida);
                    } else if (scoreHost == scoreAway) {
                        dao.contaEmpate(partida);
                    }
                    dao.criaPartida(partida);
                    dao.atualizaGolsHome(partida);
                    dao.atualizaGolsAway(partida);
                }
            }
            for (int i = 0; i < 6; i++) {
                for (int j = i + 1; j < 4; j++) {
                    Random random = new Random();
                    int scoreHost = random.nextInt(4);
                    int scoreAway = random.nextInt(4);
                    Partida partida = new Partida(grupoF[i].getId(), grupoF[j].getId(), scoreHost, scoreAway);
                    if (scoreHost > scoreAway) {
                        dao.contaVitoriaHost(partida);
                    } else if (scoreHost < scoreAway) {
                        dao.contaVitoriaAway(partida);
                    } else if (scoreHost == scoreAway) {
                        dao.contaEmpate(partida);
                    }
                    dao.criaPartida(partida);
                    dao.atualizaGolsHome(partida);
                    dao.atualizaGolsAway(partida);
                }
            }
            for (int i = 0; i < 6; i++) {
                for (int j = i + 1; j < 4; j++) {
                    Random random = new Random();
                    int scoreHost = random.nextInt(4);
                    int scoreAway = random.nextInt(4);
                    Partida partida = new Partida(grupoG[i].getId(), grupoG[j].getId(), scoreHost, scoreAway);
                    if (scoreHost > scoreAway) {
                        dao.contaVitoriaHost(partida);
                    } else if (scoreHost < scoreAway) {
                        dao.contaVitoriaAway(partida);
                    } else if (scoreHost == scoreAway) {
                        dao.contaEmpate(partida);
                    }
                    dao.criaPartida(partida);
                    dao.atualizaGolsHome(partida);
                    dao.atualizaGolsAway(partida);
                }
            }
            for (int i = 0; i < 6; i++) {
                for (int j = i + 1; j < 4; j++) {
                    Random random = new Random();
                    int scoreHost = random.nextInt(4);
                    int scoreAway = random.nextInt(4);
                    Partida partida = new Partida(grupoH[i].getId(), grupoH[j].getId(), scoreHost, scoreAway);
                    if (scoreHost > scoreAway) {
                        dao.contaVitoriaHost(partida);
                    } else if (scoreHost < scoreAway) {
                        dao.contaVitoriaAway(partida);
                    } else if (scoreHost == scoreAway) {
                        dao.contaEmpate(partida);
                    }
                    dao.criaPartida(partida);
                    dao.atualizaGolsHome(partida);
                    dao.atualizaGolsAway(partida);
                }
            }

            grupoA = dao.getTimesPorGrupo(1);
            grupoB = dao.getTimesPorGrupo(2);
            grupoC = dao.getTimesPorGrupo(3);
            grupoD = dao.getTimesPorGrupo(4);
            grupoE = dao.getTimesPorGrupo(5);
            grupoF = dao.getTimesPorGrupo(6);
            grupoG = dao.getTimesPorGrupo(7);
            grupoH = dao.getTimesPorGrupo(8);

            //Definição de times que passaram para as elimintórias - GRUPO A
            int[] pontos = new int[4];
            for (int i = 0; i < 4; i++) {
                pontos[i] = grupoA[i].getPontos();
            }
            int[] top2 = new int[2];
            int aux = 0;
            for (int i = 0; i < 4; i++) {
                if (pontos[i] >= top2[0]) {
                    aux = top2[0];
                    top2[1] = aux;
                    top2[0] = pontos[i];
                } else if (pontos[i] > top2[1] && pontos[i] < top2[0]) {
                    top2[1] = pontos[i];
                }
            }
            System.out.println(top2[0] + " " + top2[1]);
            int contador1 = 0;
            int contador2 = 0;
            int contador3 = 0;
            int contador4 = 0;
            for (int i = 0; i < 4; i++) {
                if (grupoA[i].getPontos() == top2[0] && contador1 < 1) {
                    grupoA[i].setEliminatorias(1);
                    contador1++;
                } else if (grupoA[i].getPontos() == top2[1] && contador2 < 1) {
                    grupoA[i].setEliminatorias(1);
                    contador2++;
                } else if (grupoA[i].getPontos() == top2[0] && contador1 >= 1) {
                    for (int j = 0; j < 4; j++) {
                        if (grupoA[i].getSaldoGols() - grupoA[i].getGolsSofridos() > grupoA[j].getSaldoGols() - grupoA[j].getGolsSofridos() && grupoA[j].getEliminatorias() == 1 && grupoA[i].getEliminatorias() == 0) {
                            grupoA[i].setEliminatorias(1);
                            grupoA[j].setEliminatorias(0);
                        } else if (grupoA[i].getSaldoGols() - grupoA[i].getGolsSofridos() == grupoA[j].getSaldoGols() - grupoA[j].getGolsSofridos() && grupoA[j].getEliminatorias() == 1 ) {
                            if(grupoA[i].getSaldoGols() > grupoA[j].getSaldoGols() && grupoA[i].getEliminatorias() == 0){
                                grupoA[i].setEliminatorias(1);
                                grupoA[j].setEliminatorias(0);
                            }
                        }
                    }
                } else if (grupoA[i].getPontos() == top2[1] && contador2 >= 1) {
                    for (int j = 0; j < 4; j++) {
                        if (grupoA[i].getSaldoGols() - grupoA[i].getGolsSofridos() > grupoA[j].getSaldoGols() - grupoA[j].getGolsSofridos() && grupoA[j].getEliminatorias() == 1 && grupoA[j].getPontos() == top2[1]) {
                            grupoA[i].setEliminatorias(1);
                            grupoA[j].setEliminatorias(0);
                        } else if (grupoA[i].getSaldoGols() - grupoA[i].getGolsSofridos() == grupoA[j].getSaldoGols() - grupoA[j].getGolsSofridos() && grupoA[j].getEliminatorias() == 1 && grupoA[j].getPontos() == top2[1]){
                            if(grupoA[i].getSaldoGols() > grupoA[j].getSaldoGols() && contador3 < 1){
                                grupoA[i].setEliminatorias(1);
                                grupoA[j].setEliminatorias(0);
                                contador3++;
                            }
                        }
                    }
                }
            }
            for (int i = 0; i < 4; i++) {
                if (grupoA[i].getEliminatorias() == 1) {
                    dao.defineEliminatorias(grupoA[i].getId());
                }
            }
            
            //Definição de times que passaram para as elimintórias - GRUPO B
            pontos = new int[4];
            for (int i = 0; i < 4; i++) {
                pontos[i] = grupoB[i].getPontos();
            }
            top2 = new int[2];
            aux = 0;
            for (int i = 0; i < 4; i++) {
                if (pontos[i] >= top2[0]) {
                    aux = top2[0];
                    top2[1] = aux;
                    top2[0] = pontos[i];
                } else if (pontos[i] > top2[1] && pontos[i] < top2[0]) {
                    top2[1] = pontos[i];
                }
            }
            System.out.println(top2[0] + " " + top2[1]);
            contador1 = 0;
            contador2 = 0;
            contador3 = 0;
            for (int i = 0; i < 4; i++) {
                if (grupoB[i].getPontos() == top2[0] && contador1 < 1) {
                    grupoB[i].setEliminatorias(1);
                    contador1++;
                } else if (grupoB[i].getPontos() == top2[1] && contador2 < 1) {
                    grupoB[i].setEliminatorias(1);
                    contador2++;
                } else if (grupoB[i].getPontos() == top2[0] && contador1 >= 1) {
                    for (int j = 0; j < 4; j++) {
                        if (grupoB[i].getSaldoGols() - grupoB[i].getGolsSofridos() > grupoB[j].getSaldoGols() - grupoB[j].getGolsSofridos() && grupoB[j].getEliminatorias() == 1 && grupoB[i].getEliminatorias() == 0) {
                            grupoB[i].setEliminatorias(1);
                            grupoB[j].setEliminatorias(0);
                        } else if (grupoB[i].getSaldoGols() - grupoB[i].getGolsSofridos() == grupoB[j].getSaldoGols() - grupoB[j].getGolsSofridos() && grupoB[j].getEliminatorias() == 1) {
                            if(grupoB[i].getSaldoGols() > grupoB[j].getSaldoGols() && grupoB[i].getEliminatorias() == 0){
                                grupoB[i].setEliminatorias(1);
                                grupoB[j].setEliminatorias(0);
                            }
                        }
                    }
                } else if (grupoB[i].getPontos() == top2[1] && contador2 >= 1) {
                    for (int j = 0; j < 4; j++) {
                        if (grupoB[i].getSaldoGols() - grupoB[i].getGolsSofridos() > grupoB[j].getSaldoGols() - grupoB[j].getGolsSofridos() && grupoB[j].getEliminatorias() == 1 && grupoB[j].getPontos() == top2[1]) {
                            grupoB[i].setEliminatorias(1);
                            grupoB[j].setEliminatorias(0);
                        } else if (grupoB[i].getSaldoGols() - grupoB[i].getGolsSofridos() == grupoB[j].getSaldoGols() - grupoB[j].getGolsSofridos() && grupoB[j].getEliminatorias() == 1 && grupoB[j].getPontos() == top2[1]){
                            if(grupoB[i].getSaldoGols() > grupoB[j].getSaldoGols() && contador3 < 1){
                                grupoB[i].setEliminatorias(1);
                                grupoB[j].setEliminatorias(0);
                                contador3++;
                            }
                        }
                    }
                }
            }
            for (int i = 0; i < 4; i++) {
                if (grupoB[i].getEliminatorias() == 1) {
                    dao.defineEliminatorias(grupoB[i].getId());
                }
            }
            
            //Definição de times que passaram para as elimintórias - GRUPO C
            pontos = new int[4];
            for (int i = 0; i < 4; i++) {
                pontos[i] = grupoC[i].getPontos();
            }
            top2 = new int[2];
            aux = 0;
            for (int i = 0; i < 4; i++) {
                if (pontos[i] >= top2[0]) {
                    aux = top2[0];
                    top2[1] = aux;
                    top2[0] = pontos[i];
                } else if (pontos[i] > top2[1] && pontos[i] < top2[0]) {
                    top2[1] = pontos[i];
                }
            }
            System.out.println(top2[0] + " " + top2[1]);
            contador1 = 0;
            contador2 = 0;
            contador3 = 0;
            for (int i = 0; i < 4; i++) {
                if (grupoC[i].getPontos() == top2[0] && contador1 < 1) {
                    grupoC[i].setEliminatorias(1);
                    contador1++;
                } else if (grupoC[i].getPontos() == top2[1] && contador2 < 1) {
                    grupoC[i].setEliminatorias(1);
                    contador2++;
                } else if (grupoC[i].getPontos() == top2[0] && contador1 >= 1) {
                    for (int j = 0; j < 4; j++) {
                        if (grupoC[i].getSaldoGols() - grupoC[i].getGolsSofridos() > grupoC[j].getSaldoGols() - grupoC[j].getGolsSofridos() && grupoC[j].getEliminatorias() == 1 && grupoC[i].getEliminatorias() == 0) {
                            grupoC[i].setEliminatorias(1);
                            grupoC[j].setEliminatorias(0);
                        } else if (grupoC[i].getSaldoGols() - grupoC[i].getGolsSofridos() == grupoC[j].getSaldoGols() - grupoC[j].getGolsSofridos() && grupoC[j].getEliminatorias() == 1) {
                            if(grupoC[i].getSaldoGols() > grupoC[j].getSaldoGols() && grupoC[i].getEliminatorias() == 0){
                                grupoC[i].setEliminatorias(1);
                                grupoC[j].setEliminatorias(0);
                            }
                        }
                    }
                } else if (grupoC[i].getPontos() == top2[1] && contador2 >= 1) {
                    for (int j = 0; j < 4; j++) {
                        if (grupoC[i].getSaldoGols() - grupoC[i].getGolsSofridos() > grupoC[j].getSaldoGols() - grupoC[j].getGolsSofridos() && grupoC[j].getEliminatorias() == 1 && grupoC[j].getPontos() == top2[1]) {
                            grupoC[i].setEliminatorias(1);
                            grupoC[j].setEliminatorias(0);
                        } else if (grupoC[i].getSaldoGols() - grupoC[i].getGolsSofridos() == grupoC[j].getSaldoGols() - grupoC[j].getGolsSofridos() && grupoC[j].getEliminatorias() == 1 && grupoC[j].getPontos() == top2[1]){
                            if(grupoC[i].getSaldoGols() > grupoC[j].getSaldoGols() && contador3 < 1){
                                grupoC[i].setEliminatorias(1);
                                grupoC[j].setEliminatorias(0);
                                contador3++;
                            }
                        }
                    }
                }
            }
            for (int i = 0; i < 4; i++) {
                if (grupoC[i].getEliminatorias() == 1) {
                    dao.defineEliminatorias(grupoC[i].getId());
                }
            }
            
            //Definição de times que passaram para as elimintórias - GRUPO D
            pontos = new int[4];
            for (int i = 0; i < 4; i++) {
                pontos[i] = grupoD[i].getPontos();
            }
            top2 = new int[2];
            aux = 0;
            for (int i = 0; i < 4; i++) {
                if (pontos[i] >= top2[0]) {
                    aux = top2[0];
                    top2[1] = aux;
                    top2[0] = pontos[i];
                } else if (pontos[i] > top2[1] && pontos[i] < top2[0]) {
                    top2[1] = pontos[i];
                }
            }
            System.out.println(top2[0] + " " + top2[1]);
            contador1 = 0;
            contador2 = 0;
            contador3 = 0;
            for (int i = 0; i < 4; i++) {
                if (grupoD[i].getPontos() == top2[0] && contador1 < 1) {
                    grupoD[i].setEliminatorias(1);
                    contador1++;
                } else if (grupoD[i].getPontos() == top2[1] && contador2 < 1) {
                    grupoD[i].setEliminatorias(1);
                    contador2++;
                } else if (grupoD[i].getPontos() == top2[0] && contador1 >= 1) {
                    for (int j = 0; j < 4; j++) {
                        if (grupoD[i].getSaldoGols() - grupoD[i].getGolsSofridos() > grupoD[j].getSaldoGols() - grupoD[j].getGolsSofridos() && grupoD[j].getEliminatorias() == 1 && grupoD[i].getEliminatorias() == 0) {
                            grupoD[i].setEliminatorias(1);
                            grupoD[j].setEliminatorias(0);
                        } else if (grupoD[i].getSaldoGols() - grupoD[i].getGolsSofridos() == grupoD[j].getSaldoGols() - grupoD[j].getGolsSofridos() && grupoD[j].getEliminatorias() == 1) {
                            if(grupoD[i].getSaldoGols() > grupoD[j].getSaldoGols() && grupoD[i].getEliminatorias() == 0){
                                grupoD[i].setEliminatorias(1);
                                grupoD[j].setEliminatorias(0);
                            }
                        }
                    }
                } else if (grupoD[i].getPontos() == top2[1] && contador2 >= 1) {
                    for (int j = 0; j < 4; j++) {
                        if (grupoD[i].getSaldoGols() - grupoD[i].getGolsSofridos() > grupoD[j].getSaldoGols() - grupoD[j].getGolsSofridos() && grupoD[j].getEliminatorias() == 1 && grupoD[j].getPontos() == top2[1]) {
                            grupoD[i].setEliminatorias(1);
                            grupoD[j].setEliminatorias(0);
                        } else if (grupoD[i].getSaldoGols() - grupoD[i].getGolsSofridos() == grupoD[j].getSaldoGols() - grupoD[j].getGolsSofridos() && grupoD[j].getEliminatorias() == 1 && grupoD[j].getPontos() == top2[1]){
                            if(grupoD[i].getSaldoGols() > grupoD[j].getSaldoGols() && contador3 < 1){
                                grupoD[i].setEliminatorias(1);
                                grupoD[j].setEliminatorias(0);
                                contador3++;
                            }
                        }
                    }
                }
            }
            for (int i = 0; i < 4; i++) {
                if (grupoD[i].getEliminatorias() == 1) {
                    dao.defineEliminatorias(grupoD[i].getId());
                }
            }
            
            //Definição de times que passaram para as elimintórias - GRUPO E
            pontos = new int[4];
            for (int i = 0; i < 4; i++) {
                pontos[i] = grupoE[i].getPontos();
            }
            top2 = new int[2];
            aux = 0;
            for (int i = 0; i < 4; i++) {
                if (pontos[i] >= top2[0]) {
                    aux = top2[0];
                    top2[1] = aux;
                    top2[0] = pontos[i];
                } else if (pontos[i] > top2[1] && pontos[i] < top2[0]) {
                    top2[1] = pontos[i];
                }
            }
            System.out.println(top2[0] + " " + top2[1]);
            contador1 = 0;
            contador2 = 0;
            contador3 = 0;
            for (int i = 0; i < 4; i++) {
                if (grupoE[i].getPontos() == top2[0] && contador1 < 1) {
                    grupoE[i].setEliminatorias(1);
                    contador1++;
                } else if (grupoE[i].getPontos() == top2[1] && contador2 < 1) {
                    grupoE[i].setEliminatorias(1);
                    contador2++;
                } else if (grupoE[i].getPontos() == top2[0] && contador1 >= 1) {
                    for (int j = 0; j < 4; j++) {
                        if (grupoE[i].getSaldoGols() - grupoE[i].getGolsSofridos() > grupoE[j].getSaldoGols() - grupoE[j].getGolsSofridos() && grupoE[j].getEliminatorias() == 1 && grupoE[i].getEliminatorias() == 0) {
                            grupoE[i].setEliminatorias(1);
                            grupoE[j].setEliminatorias(0);
                        } else if (grupoE[i].getSaldoGols() - grupoE[i].getGolsSofridos() == grupoE[j].getSaldoGols() - grupoE[j].getGolsSofridos() && grupoE[j].getEliminatorias() == 1) {
                            if(grupoE[i].getSaldoGols() > grupoE[j].getSaldoGols() && grupoE[i].getEliminatorias() == 0){
                                grupoE[i].setEliminatorias(1);
                                grupoE[j].setEliminatorias(0);
                            }
                        }
                    }
                } else if (grupoE[i].getPontos() == top2[1] && contador2 >= 1) {
                    for (int j = 0; j < 4; j++) {
                        if (grupoE[i].getSaldoGols() - grupoE[i].getGolsSofridos() > grupoE[j].getSaldoGols() - grupoE[j].getGolsSofridos() && grupoE[j].getEliminatorias() == 1 && grupoE[j].getPontos() == top2[1]) {
                            grupoE[i].setEliminatorias(1);
                            grupoE[j].setEliminatorias(0);
                        } else if (grupoE[i].getSaldoGols() - grupoE[i].getGolsSofridos() == grupoE[j].getSaldoGols() - grupoE[j].getGolsSofridos() && grupoE[j].getEliminatorias() == 1 && grupoE[j].getPontos() == top2[1]){
                            if(grupoE[i].getSaldoGols() > grupoE[j].getSaldoGols() && contador3 < 1){
                                grupoE[i].setEliminatorias(1);
                                grupoE[j].setEliminatorias(0);
                                contador3++;
                            }
                        }
                    }
                }
            }
            for (int i = 0; i < 4; i++) {
                if (grupoE[i].getEliminatorias() == 1) {
                    dao.defineEliminatorias(grupoE[i].getId());
                }
            }
            
            //Definição de times que passaram para as elimintórias - GRUPO F
            pontos = new int[4];
            for (int i = 0; i < 4; i++) {
                pontos[i] = grupoF[i].getPontos();
            }
            top2 = new int[2];
            aux = 0;
            for (int i = 0; i < 4; i++) {
                if (pontos[i] >= top2[0]) {
                    aux = top2[0];
                    top2[1] = aux;
                    top2[0] = pontos[i];
                } else if (pontos[i] > top2[1] && pontos[i] < top2[0]) {
                    top2[1] = pontos[i];
                }
            }
            System.out.println(top2[0] + " " + top2[1]);
            contador1 = 0;
            contador2 = 0;
            contador3 = 0;
            for (int i = 0; i < 4; i++) {
                if (grupoF[i].getPontos() == top2[0] && contador1 < 1) {
                    grupoF[i].setEliminatorias(1);
                    contador1++;
                } else if (grupoF[i].getPontos() == top2[1] && contador2 < 1) {
                    grupoF[i].setEliminatorias(1);
                    contador2++;
                } else if (grupoF[i].getPontos() == top2[0] && contador1 >= 1) {
                    for (int j = 0; j < 4; j++) {
                        if (grupoF[i].getSaldoGols() - grupoF[i].getGolsSofridos() > grupoF[j].getSaldoGols() - grupoF[j].getGolsSofridos() && grupoF[j].getEliminatorias() == 1 && grupoF[i].getEliminatorias() == 0) {
                            grupoF[i].setEliminatorias(1);
                            grupoF[j].setEliminatorias(0);
                        } else if (grupoF[i].getSaldoGols() - grupoF[i].getGolsSofridos() == grupoF[j].getSaldoGols() - grupoF[j].getGolsSofridos() && grupoF[j].getEliminatorias() == 1) {
                            if(grupoF[i].getSaldoGols() > grupoF[j].getSaldoGols() && grupoF[i].getEliminatorias() == 0){
                                grupoF[i].setEliminatorias(1);
                                grupoF[j].setEliminatorias(0);
                            }
                        }
                    }
                } else if (grupoF[i].getPontos() == top2[1] && contador2 >= 1) {
                    for (int j = 0; j < 4; j++) {
                        if (grupoF[i].getSaldoGols() - grupoF[i].getGolsSofridos() > grupoF[j].getSaldoGols() - grupoF[j].getGolsSofridos() && grupoF[j].getEliminatorias() == 1 && grupoF[j].getPontos() == top2[1]) {
                            grupoF[i].setEliminatorias(1);
                            grupoF[j].setEliminatorias(0);
                        } else if (grupoF[i].getSaldoGols() - grupoF[i].getGolsSofridos() == grupoF[j].getSaldoGols() - grupoF[j].getGolsSofridos() && grupoF[j].getEliminatorias() == 1 && grupoF[j].getPontos() == top2[1]){
                            if(grupoF[i].getSaldoGols() > grupoF[j].getSaldoGols() && contador3 < 1){
                                grupoF[i].setEliminatorias(1);
                                grupoF[j].setEliminatorias(0);
                                contador3++;
                            }
                        }
                    }
                }
            }
            for (int i = 0; i < 4; i++) {
                if (grupoF[i].getEliminatorias() == 1) {
                    dao.defineEliminatorias(grupoF[i].getId());
                }
            }
            
            //Definição de times que passaram para as elimintórias - GRUPO G
            pontos = new int[4];
            for (int i = 0; i < 4; i++) {
                pontos[i] = grupoG[i].getPontos();
            }
            top2 = new int[2];
            aux = 0;
            for (int i = 0; i < 4; i++) {
                if (pontos[i] >= top2[0]) {
                    aux = top2[0];
                    top2[1] = aux;
                    top2[0] = pontos[i];
                } else if (pontos[i] > top2[1] && pontos[i] < top2[0]) {
                    top2[1] = pontos[i];
                }
            }
            System.out.println(top2[0] + " " + top2[1]);
            contador1 = 0;
            contador2 = 0;
            contador3 = 0;
            for (int i = 0; i < 4; i++) {
                if (grupoG[i].getPontos() == top2[0] && contador1 < 1) {
                    grupoG[i].setEliminatorias(1);
                    contador1++;
                } else if (grupoG[i].getPontos() == top2[1] && contador2 < 1) {
                    grupoG[i].setEliminatorias(1);
                    contador2++;
                } else if (grupoG[i].getPontos() == top2[0] && contador1 >= 1) {
                    for (int j = 0; j < 4; j++) {
                        if (grupoG[i].getSaldoGols() - grupoG[i].getGolsSofridos() > grupoG[j].getSaldoGols() - grupoG[j].getGolsSofridos() && grupoG[j].getEliminatorias() == 1 && grupoH[i].getEliminatorias() == 0) {
                            grupoG[i].setEliminatorias(1);
                            grupoG[j].setEliminatorias(0);
                        } else if (grupoG[i].getSaldoGols() - grupoG[i].getGolsSofridos() == grupoG[j].getSaldoGols() - grupoG[j].getGolsSofridos() && grupoG[j].getEliminatorias() == 1) {
                            if(grupoG[i].getSaldoGols() > grupoG[j].getSaldoGols() && grupoH[i].getEliminatorias() == 0){
                                grupoG[i].setEliminatorias(1);
                                grupoG[j].setEliminatorias(0);
                            }
                        }
                    }
                } else if (grupoG[i].getPontos() == top2[1] && contador2 >= 1) {
                    for (int j = 0; j < 4; j++) {
                        if (grupoG[i].getSaldoGols() - grupoG[i].getGolsSofridos() > grupoG[j].getSaldoGols() - grupoG[j].getGolsSofridos() && grupoG[j].getEliminatorias() == 1 && grupoG[j].getPontos() == top2[1]) {
                            grupoG[i].setEliminatorias(1);
                            grupoG[j].setEliminatorias(0);
                        } else if (grupoG[i].getSaldoGols() - grupoG[i].getGolsSofridos() == grupoG[j].getSaldoGols() - grupoG[j].getGolsSofridos() && grupoG[j].getEliminatorias() == 1 && grupoG[j].getPontos() == top2[1]){
                            if(grupoG[i].getSaldoGols() > grupoG[j].getSaldoGols() && contador3 < 1){
                                grupoG[i].setEliminatorias(1);
                                grupoG[j].setEliminatorias(0);
                                contador3++;
                            }
                        }
                    }
                }
            }
            for (int i = 0; i < 4; i++) {
                if (grupoG[i].getEliminatorias() == 1) {
                    dao.defineEliminatorias(grupoG[i].getId());
                }
            }
            
            //Definição de times que passaram para as elimintórias - GRUPO H
            pontos = new int[4];
            for (int i = 0; i < 4; i++) {
                pontos[i] = grupoH[i].getPontos();
            }
            top2 = new int[2];
            aux = 0;
            for (int i = 0; i < 4; i++) {
                if (pontos[i] >= top2[0]) {
                    aux = top2[0];
                    top2[1] = aux;
                    top2[0] = pontos[i];
                } else if (pontos[i] > top2[1] && pontos[i] < top2[0]) {
                    top2[1] = pontos[i];
                }
            }
            System.out.println(top2[0] + " " + top2[1]);
            contador1 = 0;
            contador2 = 0;
            contador3 = 0;
            for (int i = 0; i < 4; i++) {
                if (grupoH[i].getPontos() == top2[0] && contador1 < 1) {
                    grupoH[i].setEliminatorias(1);
                    contador1++;
                } else if (grupoH[i].getPontos() == top2[1] && contador2 < 1) {
                    grupoH[i].setEliminatorias(1);
                    contador2++;
                } else if (grupoH[i].getPontos() == top2[0] && contador1 >= 1) {
                    for (int j = 0; j < 4; j++) {
                        if (grupoH[i].getSaldoGols() - grupoH[i].getGolsSofridos() > grupoH[j].getSaldoGols() - grupoH[j].getGolsSofridos() && grupoH[j].getEliminatorias() == 1) {
                            grupoH[i].setEliminatorias(1);
                            grupoH[j].setEliminatorias(0);
                        } else if (grupoH[i].getSaldoGols() - grupoH[i].getGolsSofridos() == grupoH[j].getSaldoGols() - grupoH[j].getGolsSofridos() && grupoH[j].getEliminatorias() == 1) {
                            if(grupoH[i].getSaldoGols() > grupoH[j].getSaldoGols()){
                                grupoH[i].setEliminatorias(1);
                                grupoH[j].setEliminatorias(0);
                            }
                        }
                    }
                } else if (grupoH[i].getPontos() == top2[1] && contador2 >= 1) {
                    for (int j = 0; j < 4; j++) {
                        if (grupoH[i].getSaldoGols() - grupoH[i].getGolsSofridos() > grupoH[j].getSaldoGols() - grupoH[j].getGolsSofridos() && grupoH[j].getEliminatorias() == 1 && grupoH[j].getPontos() == top2[1]) {
                            grupoH[i].setEliminatorias(1);
                            grupoH[j].setEliminatorias(0);
                        } else if (grupoH[i].getSaldoGols() - grupoH[i].getGolsSofridos() == grupoH[j].getSaldoGols() - grupoH[j].getGolsSofridos() && grupoH[j].getEliminatorias() == 1 && grupoH[j].getPontos() == top2[1]){
                            if(grupoH[i].getSaldoGols() > grupoH[j].getSaldoGols() && contador3 < 1){
                                grupoH[i].setEliminatorias(1);
                                grupoH[j].setEliminatorias(0);
                                contador3++;
                            }
                        }
                    }
                }
            }
            for (int i = 0; i < 4; i++) {
                if (grupoH[i].getEliminatorias() == 1) {
                    dao.defineEliminatorias(grupoH[i].getId());
                }
            }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        //this.dispose();
        //TelaBrackets telaBrackets = new TelaBrackets();
        //telaBrackets.setVisible(true);
    }//GEN-LAST:event_simulaGruposButtonActionPerformed

    private void registrarTimesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarTimesButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<String> times = new ArrayList<>();
        times.add(time1Grupo1TextField.getText());
        times.add(time2Grupo1TextField.getText());
        times.add(time3Grupo1TextField.getText());
        times.add(time4Grupo1TextField.getText());
        times.add(time1Grupo2TextField.getText());
        times.add(time2Grupo2TextField.getText());
        times.add(time3Grupo2TextField.getText());
        times.add(time4Grupo2TextField.getText());
        times.add(time1Grupo3TextField.getText());
        times.add(time2Grupo3TextField.getText());
        times.add(time3Grupo3TextField.getText());
        times.add(time4Grupo3TextField.getText());
        times.add(time1Grupo4TextField.getText());
        times.add(time2Grupo4TextField.getText());
        times.add(time3Grupo4TextField.getText());
        times.add(time4Grupo4TextField.getText());
        times.add(time1Grupo5TextField.getText());
        times.add(time2Grupo5TextField.getText());
        times.add(time3Grupo5TextField.getText());
        times.add(time4Grupo5TextField.getText());
        times.add(time1Grupo6TextField.getText());
        times.add(time2Grupo6TextField.getText());
        times.add(time3Grupo6TextField.getText());
        times.add(time4Grupo6TextField.getText());
        times.add(time1Grupo7TextField.getText());
        times.add(time2Grupo7TextField.getText());
        times.add(time3Grupo7TextField.getText());
        times.add(time4Grupo7TextField.getText());
        times.add(time1Grupo8TextField.getText());
        times.add(time2Grupo8TextField.getText());
        times.add(time3Grupo8TextField.getText());
        times.add(time4Grupo8TextField.getText());
        DAO dao = new DAO();
        
        boolean temVazio = false;
        boolean temRepetido = false;
        for (int i = 0; i < times.size(); i++) {
            if (times.get(i).isEmpty()){
                temVazio = true;
            }
        }
        System.out.println(times.get(4).equals(times.get(4)));
        for (int i = 0; i < 32; i++) {
            int contador = 0;
            for (int j = 0; j < 32; j++) {
                if(times.get(i).equals(times.get(j)) && contador < 1){
                    contador++;
                }
                else if (times.get(i).equals(times.get(j)) && contador >= 1) {
                    temRepetido = true;
                }
            }
        }
        if (temVazio) {
            JOptionPane.showMessageDialog(null, "Um dos campos está vazio");
            temVazio = false;
        } else if (temRepetido) {
            JOptionPane.showMessageDialog(null, "Não é possível registrar o mesmo time mais de uma vez!");
            temRepetido = false;
        } else {
        
        try {
            for (int i = 0; i < 4; i++) {
                Time time = new Time(i + 1, times.get(i), 0, 0, 0, 1, 0);
                if (dao.existeTime(time)) {
                    JOptionPane.showMessageDialog(null, "O país " + time.getNome() + " já está cadastrado");
                } else {
                    dao.inserirTime(time);
                }
            }
            for (int i = 4; i < 8; i++) {
                Time time = new Time(i + 1, times.get(i), 0, 0, 0, 2, 0);
                if (dao.existeTime(time)) {
                    JOptionPane.showMessageDialog(null, "O país " + time.getNome() + " já está cadastrado");
                } else {
                    dao.inserirTime(time);
                }
            }
            for (int i = 8; i < 12; i++) {
                Time time = new Time(i + 1, times.get(i), 0, 0, 0, 3, 0);
                if (dao.existeTime(time)) {
                    JOptionPane.showMessageDialog(null, "O país " + time.getNome() + " já está cadastrado");
                } else {
                    dao.inserirTime(time);
                }
            }
            for (int i = 12; i < 16; i++) {
                Time time = new Time(i + 1, times.get(i), 0, 0, 0, 4, 0);
                if (dao.existeTime(time)) {
                    JOptionPane.showMessageDialog(null, "O país " + time.getNome() + " já está cadastrado");
                } else {
                    dao.inserirTime(time);
                }
            }
            for (int i = 16; i < 20; i++) {
                Time time = new Time(i + 1, times.get(i), 0, 0, 0, 5, 0);
                if (dao.existeTime(time)) {
                    JOptionPane.showMessageDialog(null, "O país " + time.getNome() + " já está cadastrado");
                } else {
                    dao.inserirTime(time);
                }
            }
            for (int i = 20; i < 24; i++) {
                Time time = new Time(i + 1, times.get(i), 0, 0, 0, 6, 0);
                if (dao.existeTime(time)) {
                    JOptionPane.showMessageDialog(null, "O país " + time.getNome() + " já está cadastrado");
                } else {
                    dao.inserirTime(time);
                }
            }
            for (int i = 24; i < 28; i++) {
                Time time = new Time(i + 1, times.get(i), 0, 0, 0, 7, 0);
                if (dao.existeTime(time)) {
                    JOptionPane.showMessageDialog(null, "O país " + time.getNome() + " já está cadastrado");
                } else {
                    dao.inserirTime(time);
                }
            }
            for (int i = 28; i < 32; i++) {
                Time time = new Time(i + 1, times.get(i), 0, 0, 0, 8, 0);
                if (dao.existeTime(time)) {
                    JOptionPane.showMessageDialog(null, "O país " + time.getNome() + " já está cadastrado");
                } else {
                    dao.inserirTime(time);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_registrarTimesButtonActionPerformed

    private void mostrarJogosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarJogosButtonActionPerformed
        // TODO add your handling code here:
        try{
            DAO dao = new DAO();
            Partida[] partidas = dao.getPartidas();
            if (partidas.length == 0) {
                JOptionPane.showMessageDialog(null, "Nenhuma Partida Realizada");
            }else{
                TelaJogos tj = new TelaJogos();
                tj.setVisible(true);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_mostrarJogosButtonActionPerformed

    private void avancarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancarButtonActionPerformed
        // TODO add your handling code here:
        try{
            DAO dao = new DAO();
            Partida[] partidas = dao.getPartidas();
            if (partidas.length == 0) {
                JOptionPane.showMessageDialog(null, "Realize a simulação antes de avançar para as eliminatórias");
            }else if (dao.getClassificados().length != 16){
                JOptionPane.showMessageDialog(null, "Ocorreu algo errado, limpe os campos e tente novamente.");
            }
            else{
                TelaBrackets bc = new TelaBrackets();
                bc.setVisible(true);
                this.dispose();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_avancarButtonActionPerformed

    private void limparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparButtonActionPerformed
            time1Grupo1TextField.setText("");
            time2Grupo1TextField.setText("");
            time3Grupo1TextField.setText("");
            time4Grupo1TextField.setText("");
            time1Grupo2TextField.setText("");
            time2Grupo2TextField.setText("");
            time3Grupo2TextField.setText("");
            time4Grupo2TextField.setText("");
            time1Grupo3TextField.setText("");
            time2Grupo3TextField.setText("");
            time3Grupo3TextField.setText("");
            time4Grupo3TextField.setText("");
            time1Grupo4TextField.setText("");
            time2Grupo4TextField.setText("");
            time3Grupo4TextField.setText("");
            time4Grupo4TextField.setText("");
            time1Grupo5TextField.setText("");
            time2Grupo5TextField.setText("");
            time3Grupo5TextField.setText("");
            time4Grupo5TextField.setText("");
            time1Grupo6TextField.setText("");
            time2Grupo6TextField.setText("");
            time3Grupo6TextField.setText("");
            time4Grupo6TextField.setText("");
            time1Grupo7TextField.setText("");
            time2Grupo7TextField.setText("");
            time3Grupo7TextField.setText("");
            time4Grupo7TextField.setText("");
            time1Grupo8TextField.setText("");
            time2Grupo8TextField.setText("");
            time3Grupo8TextField.setText("");
            time4Grupo8TextField.setText("");
            DAO dao = new DAO();
            try{
                dao.LimparJogos();
                dao.LimparTimes();
            } catch(Exception e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_limparButtonActionPerformed

    private void time1Grupo2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time1Grupo2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time1Grupo2TextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGrupos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avancarButton;
    private javax.swing.JButton gruposOficiaisButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton limparButton;
    private javax.swing.JButton mostrarJogosButton;
    private javax.swing.JButton registrarTimesButton;
    private javax.swing.JButton simulaGruposButton;
    private javax.swing.JTextField time1Grupo1TextField;
    private javax.swing.JTextField time1Grupo2TextField;
    private javax.swing.JTextField time1Grupo3TextField;
    private javax.swing.JTextField time1Grupo4TextField;
    private javax.swing.JTextField time1Grupo5TextField;
    private javax.swing.JTextField time1Grupo6TextField;
    private javax.swing.JTextField time1Grupo7TextField;
    private javax.swing.JTextField time1Grupo8TextField;
    private javax.swing.JTextField time2Grupo1TextField;
    private javax.swing.JTextField time2Grupo2TextField;
    private javax.swing.JTextField time2Grupo3TextField;
    private javax.swing.JTextField time2Grupo4TextField;
    private javax.swing.JTextField time2Grupo5TextField;
    private javax.swing.JTextField time2Grupo6TextField;
    private javax.swing.JTextField time2Grupo7TextField;
    private javax.swing.JTextField time2Grupo8TextField;
    private javax.swing.JTextField time3Grupo1TextField;
    private javax.swing.JTextField time3Grupo2TextField;
    private javax.swing.JTextField time3Grupo3TextField;
    private javax.swing.JTextField time3Grupo4TextField;
    private javax.swing.JTextField time3Grupo5TextField;
    private javax.swing.JTextField time3Grupo6TextField;
    private javax.swing.JTextField time3Grupo7TextField;
    private javax.swing.JTextField time3Grupo8TextField;
    private javax.swing.JTextField time4Grupo1TextField;
    private javax.swing.JTextField time4Grupo2TextField;
    private javax.swing.JTextField time4Grupo3TextField;
    private javax.swing.JTextField time4Grupo4TextField;
    private javax.swing.JTextField time4Grupo5TextField;
    private javax.swing.JTextField time4Grupo6TextField;
    private javax.swing.JTextField time4Grupo7TextField;
    private javax.swing.JTextField time4Grupo8TextField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
